version: '3'

services:
  geofence-database:
    image: mongo
    container_name: geofence_database
    networks:
      - geofence-net
    command: mongod --port 27018
    ports:
      - "27018:27018"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - geofence-net

networks:
  geofence-net:
    name: geofence-net